name: windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  windows:
    strategy:
      matrix:
        include:
          - os: windows-2022
            arch: x64
            base_name: windows-x86_64

    runs-on: ${{ matrix.os }}

    env:
      gst_version: 1.26.8

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install build tools
        run: pipx install meson ninja conan cmake

      - name: Setup compiler
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install conan profile
        run: conan config install .github/conan_profiles/${{ matrix.os }}-${{ matrix.arch }} -tf profiles

      - name: Cache conan
        uses: actions/cache@v4
        id: cache-conan
        with:
          path: ~/.conan2
          key: ${{ matrix.base_name }}-conan-srt
          restore-keys: ${{ matrix.base_name }}-conan-

      - name: Install SRT 
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: conan install --requires srt/1.5.4 --build=missing -pr:a ${{ matrix.os }}-${{ matrix.arch }} -s build_type=Release -g PkgConfigDeps

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.*
          cache: true
          dir: ${{ github.workspace }}
          modules: 'qtshadertools'

      - name: Cache gstreamer
        uses: actions/cache@v4
        id: cache-gstreamer
        with:
          path: gstreamer
          key: ${{ matrix.base_name }}-gstreamer-${{ env.gst_version }}
          restore-keys: ${{ matrix.base_name }}-gstreamer-

      - name: Clone
        if: steps.cache-gstreamer.outputs.cache-hit != 'true'
        shell: bash
        run: |
          if [ ! -d gstreamer ]; then
            git clone --depth 1 --branch ${{ env.gst_version }} https://gitlab.freedesktop.org/gstreamer/gstreamer.git
          fi

      - name: Configure meson
        working-directory: gstreamer
        env:
          meson_args: >
            --prefix="${{ runner.temp }}\gstreamer"
            -Dbase=enabled
            -Dgood=enabled
            -Dbad=enabled
            -Dgst-plugins-bad:srt=enabled
            -Dgst-plugins-bad:qsv=enabled
            -Dgst-plugins-bad:d3d11=enabled
            -Dgst-plugins-bad:qt6d3d11=enabled
            -Dlibav=enabled
            -Dlibxml2:python=false
          PKG_CONFIG_PATH: ${{ github.workspace }};${{ env.PKG_CONFIG_PATH }}
        shell: cmd
        run: |
          if not exist builddir (
            meson setup builddir ${{ env.meson_args }}
          ) else (
            meson setup --reconfigure builddir ${{ env.meson_args }}
          )

      - name: Build
        working-directory: gstreamer
        run: ninja -C builddir

      - name: Install
        working-directory: gstreamer
        run: meson install -C builddir

      - name: Zip
        run: 7z a ${{ matrix.base_name }}-${{ env.gst_version }}.zip "${{ runner.temp }}\gstreamer"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.base_name }}
          path: ${{ matrix.base_name }}-${{ env.gst_version }}.zip
